project:
  type: website
  output-dir: docs

website:
  title: "DSCI 522 Slides"
  navbar:
    left:
      - text: "Home"
        href: index.html
      - text: "Lectures"
        menu:
          - text: "Lecture 1"
            href: lectures/lec1.html
          - text: "Lecture 2"
            href: lectures/lec2.html
          - text: "Lecture 3"
            href: lectures/lec3.html
          - text: "Lecture 4"
            href: lectures/lec4.html
          - text: "Lecture 5"
            href: lectures/lec5.html
      - text: "Labs"
        menu:
          - text: "Lab 1"
            href: labs/lab1-intro.html
      - text: "Cheatsheets"
        menu:
          - text: "Command Line"
            href: cheatsheets/cheatsheet_command_line.html
          - text: "Conda & Conda-lock"
            href: cheatsheets/cheatsheet_conda.html
          - text: "Docker & Docker Compose"
            href: cheatsheets/cheatsheet_docker.html

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

