project:
  type: website
  output-dir: docs

website:
  title: "DSCI 522 Slides"
  navbar:
    left:
      - text: "Home"
        href: index.html
      - text: "Lectures"
        menu:
          - text: "Lecture 1"
            href: lec1.html
      - text: "Labs"
        menu:
          - text: "Lab 1"
            href: lab1-intro.html

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

