project:
  type: website
  output-dir: docs

website:
  title: "DSCI 522 Slides"
  navbar:
    left:
      - text: "Home"
        href: index.html
      - text: "Lectures"
        menu:
          - text: "Lecture 1"
            href: lec1.html
          - text: "Lecture 2"
            href: lec2.html
          - text: "Lecture 3"
            href: lec3.html
          - text: "Lecture 4"
            href: lec4.html
      - text: "Labs"
        menu:
          - text: "Lab 1"
            href: lab1-intro.html
      - text: "Cheatsheets"
        menu:
          - text: "Conda & Conda-lock"
            href: cheatsheet_conda.html
          - text: "Docker & Docker Compose"
            href: cheatsheet_docker.html

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

